#!/usr/bin/env python3
"""Export current database state as seed.py.

Connects to the database, reads all tables, and prints a complete seed.py
module to stdout.  Redirect to overwrite the seed file:

    cd backend
    DATABASE_URL=postgresql+asyncpg://... python -m scripts.export_seed > app/seed.py

The async DATABASE_URL is accepted as-is (the script swaps the driver
to psycopg2 automatically).
"""

import os
import sys
import textwrap

from sqlalchemy import create_engine, text

# ── DB connection ────────────────────────────────────────────────────────────

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://rbms:rbmspass@localhost:5432/rbms",
)

# Swap async driver for sync
sync_url = DATABASE_URL.replace("+asyncpg", "").replace("postgresql://", "postgresql+psycopg2://")
if not sync_url.startswith("postgresql"):
    sync_url = "postgresql+psycopg2" + sync_url[sync_url.index("://"):]

engine = create_engine(sync_url)


# ── Helpers ──────────────────────────────────────────────────────────────────

def _quote(val):
    """Return a Python-literal string for a value."""
    if val is None:
        return "None"
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, int):
        return str(val)
    # String — use repr for safe quoting
    return repr(str(val))


def _fmt_row(row: dict, cols: list[str]) -> str:
    """Format a single row dict as a Python dict literal."""
    parts = []
    for c in cols:
        parts.append(f'"{c}": {_quote(row[c])}')
    return "    {" + ", ".join(parts) + "},"


def _dump_table(conn, table: str, cols: list[str], order_by: str | None = None) -> list[dict]:
    """Query a table and return rows as dicts."""
    sql = f"SELECT {', '.join(cols)} FROM {table}"
    if order_by:
        sql += f" ORDER BY {order_by}"
    result = conn.execute(text(sql))
    return [dict(row._mapping) for row in result]


# ── Table definitions (column lists + ordering) ─────────────────────────────

TABLES = [
    ("ORGS",           "organizations",             ["id", "name", "parent_id"],                           None),
    ("USERS",          "users",                     ["id", "username", "description", "password_hash",
                                                     "password", "org_id", "is_superadmin", "is_org_admin"], "username"),
    ("ROLES",          "roles",                     ["id", "name", "org_id", "is_org_role"],                "org_id, is_org_role DESC, name"),
    ("ROLE_INCLUSIONS","role_inclusions",            ["role_id", "included_role_id"],                       None),
    ("RESOURCES",      "resources",                 ["id", "name", "resource_type", "org_id"],              "org_id, name"),
    ("PERMISSIONS",    "role_resource_permissions",  ["role_id", "resource_id", "permission_bits"],          None),
    ("USER_ROLES",     "user_roles",                ["user_id", "role_id"],                                 None),
    ("EXCHANGES",      "org_exchanges",             ["id", "org_a_id", "org_b_id"],                        None),
    ("EXCHANGE_ROLES", "exchange_roles",             ["exchange_id", "role_id"],                             None),
]


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    with engine.connect() as conn:
        # Topologically order orgs (parents first)
        all_orgs = _dump_table(conn, "organizations", ["id", "name", "parent_id"])
        org_by_id = {o["id"]: o for o in all_orgs}
        ordered_orgs = []
        placed = set()

        def _place(org):
            if org["id"] in placed:
                return
            if org["parent_id"] and org["parent_id"] not in placed:
                parent = org_by_id.get(org["parent_id"])
                if parent:
                    _place(parent)
            ordered_orgs.append(org)
            placed.add(org["id"])

        for o in all_orgs:
            _place(o)

        # Build org name lookup for comments
        org_names = {o["id"]: o["name"] for o in all_orgs}

        # Print header
        print('"""Demo seed data — auto-generated by scripts/export_seed.py."""')
        print()
        print("import uuid")
        print()
        print("import bcrypt")
        print("from sqlalchemy import text")
        print("from sqlalchemy.ext.asyncio import AsyncSession")
        print()
        print()
        print('NAMESPACE = uuid.UUID("e58ed763-928c-4155-bee9-fae2cee20735")')
        print()
        print()
        print("def _id(key: str) -> str:")
        print("    return str(uuid.uuid5(NAMESPACE, key))")
        print()
        print()
        print("def _pw(plain: str) -> str:")
        print("    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()")
        print()

        # Print orgs (special-cased for topological order)
        print()
        print("# " + "─" * 76)
        print()
        print("ORGS = [")
        for o in ordered_orgs:
            print(_fmt_row(o, ["id", "name", "parent_id"]))
        print("]")

        # Print remaining tables
        for var_name, table, cols, order_by in TABLES:
            if var_name == "ORGS":
                continue  # already printed
            print()
            print("# " + "─" * 76)
            print()
            rows = _dump_table(conn, table, cols, order_by)
            type_hint = ": list[dict]" if not rows else ""
            print(f"{var_name}{type_hint} = [")
            for row in rows:
                print(_fmt_row(row, cols))
            print("]")

        # Print reset function
        print()
        print()
        print("# " + "─" * 76)
        print()
        print(textwrap.dedent('''\
            _ALL_TABLES = [
                ("organizations", ORGS),
                ("users", USERS),
                ("roles", ROLES),
                ("role_inclusions", ROLE_INCLUSIONS),
                ("resources", RESOURCES),
                ("role_resource_permissions", PERMISSIONS),
                ("user_roles", USER_ROLES),
                ("org_exchanges", EXCHANGES),
                ("exchange_roles", EXCHANGE_ROLES),
            ]


            async def reset(db: AsyncSession) -> None:
                """Truncate all tables and re-insert seed data."""
                await db.execute(text(
                    "TRUNCATE organizations, users, resources, roles, "
                    "role_inclusions, role_resource_permissions, user_roles, "
                    "org_exchanges, exchange_roles CASCADE"
                ))

                for table, rows in _ALL_TABLES:
                    if not rows:
                        continue
                    cols = list(rows[0].keys())
                    col_list = ", ".join(cols)
                    val_list = ", ".join(f":{c}" for c in cols)
                    stmt = text(f"INSERT INTO {table} ({col_list}) VALUES ({val_list})")
                    for row in rows:
                        await db.execute(stmt, row)

                await db.commit()'''))


if __name__ == "__main__":
    main()
