"""Demo seed data — auto-generated by scripts/export_seed.py."""

import uuid

import bcrypt
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


NAMESPACE = uuid.UUID("e58ed763-928c-4155-bee9-fae2cee20735")


def _id(key: str) -> str:
    return str(uuid.uuid5(NAMESPACE, key))


def _pw(plain: str) -> str:
    return bcrypt.hashpw(plain.encode(), bcrypt.gensalt()).decode()


# ────────────────────────────────────────────────────────────────────────────

ORGS = [
    {"id": 'b2a1640b-8454-535c-8424-0daeb907aebb', "name": 'root', "parent_id": None},
    {"id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "name": 'Організм А', "parent_id": None},
    {"id": 'c0994677-1027-4168-ab12-ef454d229097', "name": 'Організм Б', "parent_id": None},
    {"id": 'ad5a64e3-736d-45cb-b581-c5da1cc90f0b', "name": 'Організм В', "parent_id": None},
    {"id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "name": 'Підрозділ А 1', "parent_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5'},
    {"id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "name": 'Підрозділ А 2', "parent_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5'},
    {"id": '2453860e-4a75-4d86-a4ed-36d05c29458e', "name": 'Підрозділ Б 1', "parent_id": 'c0994677-1027-4168-ab12-ef454d229097'},
    {"id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02', "name": 'Підрозділ Б 2', "parent_id": 'c0994677-1027-4168-ab12-ef454d229097'},
]

# ────────────────────────────────────────────────────────────────────────────

USERS = [
    {"id": 'c6225058-a782-5ea0-b62c-9ce2682f531b', "username": 'admin', "description": 'Superadmin account', "password_hash": '$2b$12$Ssb4tJfJZnqNlZGB8RA.qOVINd3UUk2hoybzgP0IvmzcUwpp03TrG', "password": 'admin123', "org_id": 'b2a1640b-8454-535c-8424-0daeb907aebb', "is_superadmin": True, "is_org_admin": True},
    {"id": '300e72e5-68f5-40bf-84de-020007a11ab2', "username": 'адмін А', "description": '', "password_hash": '$2b$12$Y5KNvUXlqxmLezpEo.5JL.eikcqSWXfMvbbX12eqf2bUqzDuSE2/S', "password": '123', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_superadmin": False, "is_org_admin": True},
    {"id": '48c2998e-01a3-4fff-9e23-bb3cd14fef4f', "username": 'адмін Б', "description": '', "password_hash": '$2b$12$jPyNZwsj9zmQ6ZPcRM2znucsFifWSQO4HeIPsSQK16VHp.rpiQ3cO', "password": '', "org_id": 'c0994677-1027-4168-ab12-ef454d229097', "is_superadmin": False, "is_org_admin": True},
    {"id": '9892e940-eb58-4a41-ab4c-1fa24bd88790', "username": 'диспетчер А', "description": '', "password_hash": '$2b$12$Mcaz8lYZTjJwEtkd.J1Zr.I3L3lBeVyNKd8aUgNrIQqhEQWGto1fa', "password": '', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_superadmin": False, "is_org_admin": False},
    {"id": 'aab404d4-a4f3-46d0-b332-61fa95c74d1a', "username": 'пілот 1', "description": '', "password_hash": '$2b$12$iF/3HtSDvVA6REhzYgu8HOJNKKaRzQHaZq.95nYByYn85mcBlhD6q', "password": '123', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "is_superadmin": False, "is_org_admin": False},
    {"id": '2bdc1268-5892-4469-a8c0-d02c9389d208', "username": 'пілот 2', "description": '', "password_hash": '$2b$12$l5J0rcFYsThvLVjBFJWPFeXcr4FRL09cUsc5Z1N3axOLasavLKX7O', "password": '123', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "is_superadmin": False, "is_org_admin": False},
    {"id": 'f785d79a-d53a-43b9-80ca-8579644d5500', "username": 'пілот 3', "description": '', "password_hash": '$2b$12$G0WUGsUy7FYlKr2J10TUtey6JKmwrXeWJP.ojx/5oIfIqVFIY3jly', "password": '123', "org_id": '2453860e-4a75-4d86-a4ed-36d05c29458e', "is_superadmin": False, "is_org_admin": False},
    {"id": '48e48388-831f-4076-818c-42c2716aadae', "username": 'пілот 4', "description": '', "password_hash": '$2b$12$HBCukWW6BI7pao69UtNcLeA4BpqC5HMfJVIEjF5meITBrXavszvpy', "password": '123', "org_id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02', "is_superadmin": False, "is_org_admin": False},
    {"id": '654b9245-5a7f-4576-8ba4-e8444c9d7505', "username": 'суміжник', "description": '', "password_hash": '$2b$12$B/m79kG8DGF8C1eXPDCmQ.DHVoDStoOLgD1hU8scHOT3UklzFXRXG', "password": '', "org_id": 'ad5a64e3-736d-45cb-b581-c5da1cc90f0b', "is_superadmin": False, "is_org_admin": False},
]

# ────────────────────────────────────────────────────────────────────────────

ROLES = [
    {"id": '999f34f3-d60a-449a-a89f-42d94bc997c4', "name": '@members', "org_id": '2453860e-4a75-4d86-a4ed-36d05c29458e', "is_org_role": True},
    {"id": 'd4c40c33-5478-4b78-a3a3-746aa28fead0', "name": 'екіпаж', "org_id": '2453860e-4a75-4d86-a4ed-36d05c29458e', "is_org_role": False},
    {"id": '06ffa210-b955-4cf6-80ed-71dfff4ac4c8', "name": 'на загал', "org_id": '2453860e-4a75-4d86-a4ed-36d05c29458e', "is_org_role": False},
    {"id": 'e2fecbd8-0921-44c0-adc2-b9b0cb43c52b', "name": '@members', "org_id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02', "is_org_role": True},
    {"id": '25fe37cd-3dc4-4a3f-a008-99aab1408024', "name": 'екіпаж', "org_id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02', "is_org_role": False},
    {"id": '9572d981-cbc2-403d-8206-1f0d9ef87a00', "name": 'на загал', "org_id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02', "is_org_role": False},
    {"id": '99f7b256-692c-4d32-a226-dd97a64a42b4', "name": '@members', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "is_org_role": True},
    {"id": 'd6f2d8fc-1f9c-4c09-8da8-c9b3ee097a14', "name": 'перегляд внутрішній', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "is_org_role": False},
    {"id": '1c12ddf3-e251-43a6-b947-55dcf694f65e', "name": 'перегляд загальний', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "is_org_role": False},
    {"id": 'dc226a75-7a3e-46ba-b3d4-5ef8bcdec282', "name": 'пілот', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c', "is_org_role": False},
    {"id": '16d92234-f830-4004-8a38-b2872a79acd8', "name": '@members', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "is_org_role": True},
    {"id": '72705f37-4cf2-4d36-80f0-b90e341162c6', "name": 'перегляд внутрішній', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "is_org_role": False},
    {"id": '0c9af7be-2855-406b-be2c-94b65228b96d', "name": 'перегляд загальний', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "is_org_role": False},
    {"id": '16394525-6105-499d-86a2-55199db5b79c', "name": 'пілот', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224', "is_org_role": False},
    {"id": '6d4c86e3-6bb7-46c2-9e4a-cb35120d7251', "name": '@members', "org_id": 'ad5a64e3-736d-45cb-b581-c5da1cc90f0b', "is_org_role": True},
    {"id": 'c38614a2-939a-4756-a18f-9e0ad05f543b', "name": 'керівник', "org_id": 'ad5a64e3-736d-45cb-b581-c5da1cc90f0b', "is_org_role": False},
    {"id": '4b7738de-4980-53f2-8d34-83ba5a6b20ee', "name": '@members', "org_id": 'b2a1640b-8454-535c-8424-0daeb907aebb', "is_org_role": True},
    {"id": '7080921c-49ce-4d07-b3be-e695f82e11f3', "name": 'диспетчер', "org_id": 'b2a1640b-8454-535c-8424-0daeb907aebb', "is_org_role": False},
    {"id": 'e99768b9-a8af-45f2-b045-4dd416597e4f', "name": '@members', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_org_role": True},
    {"id": 'b53f630e-2b16-4aec-afff-37e83647ec82', "name": 'диспетчер', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_org_role": False},
    {"id": '953da956-5060-498a-92a2-0d86001bc3af', "name": 'для суміжників', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_org_role": False},
    {"id": 'f5f3304b-894a-4808-88f7-e012f5ace7d9', "name": 'перегляд суміжників', "org_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "is_org_role": False},
    {"id": 'e91fe54d-dbb1-4d57-a9fe-8a4c9eaaa803', "name": '@members', "org_id": 'c0994677-1027-4168-ab12-ef454d229097', "is_org_role": True},
    {"id": '4ce399e7-faa9-443b-9258-205097df5505', "name": 'для А', "org_id": 'c0994677-1027-4168-ab12-ef454d229097', "is_org_role": False},
]

# ────────────────────────────────────────────────────────────────────────────

ROLE_INCLUSIONS = [
    {"role_id": '16d92234-f830-4004-8a38-b2872a79acd8', "included_role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f'},
    {"role_id": '99f7b256-692c-4d32-a226-dd97a64a42b4', "included_role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f'},
    {"role_id": '999f34f3-d60a-449a-a89f-42d94bc997c4', "included_role_id": 'e91fe54d-dbb1-4d57-a9fe-8a4c9eaaa803'},
    {"role_id": 'e2fecbd8-0921-44c0-adc2-b9b0cb43c52b', "included_role_id": 'e91fe54d-dbb1-4d57-a9fe-8a4c9eaaa803'},
    {"role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f', "included_role_id": '1c12ddf3-e251-43a6-b947-55dcf694f65e'},
    {"role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f', "included_role_id": '0c9af7be-2855-406b-be2c-94b65228b96d'},
    {"role_id": '953da956-5060-498a-92a2-0d86001bc3af', "included_role_id": '0c9af7be-2855-406b-be2c-94b65228b96d'},
    {"role_id": '953da956-5060-498a-92a2-0d86001bc3af', "included_role_id": '1c12ddf3-e251-43a6-b947-55dcf694f65e'},
    {"role_id": 'b53f630e-2b16-4aec-afff-37e83647ec82', "included_role_id": '72705f37-4cf2-4d36-80f0-b90e341162c6'},
    {"role_id": 'b53f630e-2b16-4aec-afff-37e83647ec82', "included_role_id": 'd6f2d8fc-1f9c-4c09-8da8-c9b3ee097a14'},
    {"role_id": '7080921c-49ce-4d07-b3be-e695f82e11f3', "included_role_id": 'b53f630e-2b16-4aec-afff-37e83647ec82'},
    {"role_id": '4ce399e7-faa9-443b-9258-205097df5505', "included_role_id": '06ffa210-b955-4cf6-80ed-71dfff4ac4c8'},
    {"role_id": '4ce399e7-faa9-443b-9258-205097df5505', "included_role_id": '9572d981-cbc2-403d-8206-1f0d9ef87a00'},
    {"role_id": 'c38614a2-939a-4756-a18f-9e0ad05f543b', "included_role_id": '953da956-5060-498a-92a2-0d86001bc3af'},
    {"role_id": '16394525-6105-499d-86a2-55199db5b79c', "included_role_id": 'f5f3304b-894a-4808-88f7-e012f5ace7d9'},
    {"role_id": 'dc226a75-7a3e-46ba-b3d4-5ef8bcdec282', "included_role_id": 'f5f3304b-894a-4808-88f7-e012f5ace7d9'},
]

# ────────────────────────────────────────────────────────────────────────────

RESOURCES = [
    {"id": 'ae2962d9-6a1e-462b-90a5-2d032365137f', "name": 'відео загал Б 1', "resource_type": 'video', "org_id": '2453860e-4a75-4d86-a4ed-36d05c29458e'},
    {"id": '728de878-c1ea-444a-9dff-d08c377e0715', "name": 'відео загал Б 2', "resource_type": 'video', "org_id": '2603a72c-97a4-4e29-bd03-0dd1d9518e02'},
    {"id": 'aa6d7fde-4bd1-42e8-a8cf-6061f7b30076', "name": 'відео загал А 2', "resource_type": 'video', "org_id": '2d9fb7de-e7b8-4472-8517-eaf40a98331c'},
    {"id": 'e7bbe7ab-4519-4816-9151-1d2ada0feeee', "name": 'відео внутрішнє', "resource_type": 'video', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224'},
    {"id": '4cf93a5d-2a32-49a0-93ae-2736138e4588', "name": 'відео загал А 1', "resource_type": 'video', "org_id": 'a019d1d7-0b33-4e7c-9964-9021eba0b224'},
]

# ────────────────────────────────────────────────────────────────────────────

PERMISSIONS = [
    {"role_id": '72705f37-4cf2-4d36-80f0-b90e341162c6', "resource_id": '4cf93a5d-2a32-49a0-93ae-2736138e4588', "permission_bits": 3},
    {"role_id": '0c9af7be-2855-406b-be2c-94b65228b96d', "resource_id": '4cf93a5d-2a32-49a0-93ae-2736138e4588', "permission_bits": 1},
    {"role_id": '72705f37-4cf2-4d36-80f0-b90e341162c6', "resource_id": 'e7bbe7ab-4519-4816-9151-1d2ada0feeee', "permission_bits": 3},
    {"role_id": '16394525-6105-499d-86a2-55199db5b79c', "resource_id": 'e7bbe7ab-4519-4816-9151-1d2ada0feeee', "permission_bits": 7},
    {"role_id": '16394525-6105-499d-86a2-55199db5b79c', "resource_id": '4cf93a5d-2a32-49a0-93ae-2736138e4588', "permission_bits": 7},
    {"role_id": 'd6f2d8fc-1f9c-4c09-8da8-c9b3ee097a14', "resource_id": 'aa6d7fde-4bd1-42e8-a8cf-6061f7b30076', "permission_bits": 3},
    {"role_id": '1c12ddf3-e251-43a6-b947-55dcf694f65e', "resource_id": 'aa6d7fde-4bd1-42e8-a8cf-6061f7b30076', "permission_bits": 1},
    {"role_id": 'dc226a75-7a3e-46ba-b3d4-5ef8bcdec282', "resource_id": 'aa6d7fde-4bd1-42e8-a8cf-6061f7b30076', "permission_bits": 7},
    {"role_id": '25fe37cd-3dc4-4a3f-a008-99aab1408024', "resource_id": '728de878-c1ea-444a-9dff-d08c377e0715', "permission_bits": 7},
    {"role_id": 'd4c40c33-5478-4b78-a3a3-746aa28fead0', "resource_id": 'ae2962d9-6a1e-462b-90a5-2d032365137f', "permission_bits": 7},
]

# ────────────────────────────────────────────────────────────────────────────

USER_ROLES = [
    {"user_id": 'c6225058-a782-5ea0-b62c-9ce2682f531b', "role_id": '4b7738de-4980-53f2-8d34-83ba5a6b20ee'},
    {"user_id": 'aab404d4-a4f3-46d0-b332-61fa95c74d1a', "role_id": '16d92234-f830-4004-8a38-b2872a79acd8'},
    {"user_id": '2bdc1268-5892-4469-a8c0-d02c9389d208', "role_id": '99f7b256-692c-4d32-a226-dd97a64a42b4'},
    {"user_id": '9892e940-eb58-4a41-ab4c-1fa24bd88790', "role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f'},
    {"user_id": '300e72e5-68f5-40bf-84de-020007a11ab2', "role_id": 'e99768b9-a8af-45f2-b045-4dd416597e4f'},
    {"user_id": '654b9245-5a7f-4576-8ba4-e8444c9d7505', "role_id": '6d4c86e3-6bb7-46c2-9e4a-cb35120d7251'},
    {"user_id": '654b9245-5a7f-4576-8ba4-e8444c9d7505', "role_id": 'c38614a2-939a-4756-a18f-9e0ad05f543b'},
    {"user_id": 'f785d79a-d53a-43b9-80ca-8579644d5500', "role_id": '999f34f3-d60a-449a-a89f-42d94bc997c4'},
    {"user_id": '48e48388-831f-4076-818c-42c2716aadae', "role_id": 'e2fecbd8-0921-44c0-adc2-b9b0cb43c52b'},
    {"user_id": '48c2998e-01a3-4fff-9e23-bb3cd14fef4f', "role_id": 'e91fe54d-dbb1-4d57-a9fe-8a4c9eaaa803'},
    {"user_id": 'aab404d4-a4f3-46d0-b332-61fa95c74d1a', "role_id": '16394525-6105-499d-86a2-55199db5b79c'},
    {"user_id": '2bdc1268-5892-4469-a8c0-d02c9389d208', "role_id": 'dc226a75-7a3e-46ba-b3d4-5ef8bcdec282'},
]

# ────────────────────────────────────────────────────────────────────────────

EXCHANGES = [
    {"id": 'bfaf7b25-976a-4414-861c-5c697c40f324', "org_a_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5', "org_b_id": 'c0994677-1027-4168-ab12-ef454d229097'},
    {"id": '0ecf9e18-79e7-4f53-94ee-3754661e4861', "org_a_id": 'ad5a64e3-736d-45cb-b581-c5da1cc90f0b', "org_b_id": 'b53cbc8e-b418-4910-855e-c9b9eb3b76d5'},
]

# ────────────────────────────────────────────────────────────────────────────

EXCHANGE_ROLES = [
    {"exchange_id": 'bfaf7b25-976a-4414-861c-5c697c40f324', "role_id": 'b53f630e-2b16-4aec-afff-37e83647ec82'},
    {"exchange_id": '0ecf9e18-79e7-4f53-94ee-3754661e4861', "role_id": 'c38614a2-939a-4756-a18f-9e0ad05f543b'},
]


# ────────────────────────────────────────────────────────────────────────────

_ALL_TABLES = [
    ("organizations", ORGS),
    ("users", USERS),
    ("roles", ROLES),
    ("role_inclusions", ROLE_INCLUSIONS),
    ("resources", RESOURCES),
    ("role_resource_permissions", PERMISSIONS),
    ("user_roles", USER_ROLES),
    ("org_exchanges", EXCHANGES),
    ("exchange_roles", EXCHANGE_ROLES),
]


async def reset(db: AsyncSession) -> None:
    """Truncate all tables and re-insert seed data."""
    await db.execute(text(
        "TRUNCATE organizations, users, resources, roles, "
        "role_inclusions, role_resource_permissions, user_roles, "
        "org_exchanges, exchange_roles CASCADE"
    ))

    for table, rows in _ALL_TABLES:
        if not rows:
            continue
        cols = list(rows[0].keys())
        col_list = ", ".join(cols)
        val_list = ", ".join(f":{c}" for c in cols)
        stmt = text(f"INSERT INTO {table} ({col_list}) VALUES ({val_list})")
        for row in rows:
            await db.execute(stmt, row)

    await db.commit()
